### ISSUE TITLE
CLI to display stacks' container digest version

### ISSUE THREAD

**Issue by smcclem** [kabanero-io/kabanero-command-line#212]
New "Governance Policy" is being introduced into Kabanero.  The CLI needs to expose new metadata for the active stacks, so that Champ can use the command line to verify and validate container digests of his activate stacks when required.

See more:  https://github.com/kabanero-io/kabanero-foundation/blob/master/design/digest.md#kabanero-cli-and-rest-apis

**Comment by s1cyan** [comment]
**Part 1**

After having a meeting with design- it was decided that in `list`, we will have another column to the right after status, that indicates `pass` or `fail` for matching digests. having the sha after every single stack and version doesn't seem necessary because champ won't always need it.


**Part 2**

Tentatively there was also discussion about making a ` kabanero describe <stack> <version` to essentially list out the details of one stack, most of the information is currently available in list, but with the digest. This is in anticipation of future work items where we want to provide even more information to champ and we can't just keep adding new columns to the `list` command
